In [122]:
import pandas as pd
import numpy as np
df = pd.read_csv('model_data.csv').drop(columns = ['Unnamed: 0'])

# Data Prepration, removed distance

In [123]:
df = df[['prev_CW/SA_rate', 'S_create2SA_Create', 'S_Create2Start_Time',
       'SA_Create2Start_Time', 'U_create2now', 'U_approve2now', 'type_d',
       'segmentName_d', 'net_pay', 'target']]

In [124]:
df.dropna(inplace = True) # If True, do operation inplace and return None.

In [125]:
# make a dataset that num of tar = num of non tar
import random
df_tar = df[df['target']==1].reset_index(drop = True)
df_nontar = df[df['target']==0].reset_index(drop = True)

number_of_tar = df_tar.shape[0]
random_indices = random.sample(range(len(df_nontar)), int(number_of_tar))
df_nontar = df_nontar[df_nontar.index.isin(random_indices)]

# concat
df = pd.concat([df_tar, df_nontar])

In [126]:
# standardlize
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(df.drop('target',axis=1))
scaled_features = scaler.transform(df.drop('target',axis=1))

In [127]:
# train test
X = pd.DataFrame(scaled_features,columns=df.columns[:-1])
y = df['target']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size=0.30)

# Decision Trees

In [128]:
# fit
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)

DecisionTreeClassifier()

In [129]:
# predict
predictions = dtree.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[770 538]
 [534 780]]


              precision    recall  f1-score   support

           0       0.59      0.59      0.59      1308
           1       0.59      0.59      0.59      1314

    accuracy                           0.59      2622
   macro avg       0.59      0.59      0.59      2622
weighted avg       0.59      0.59      0.59      2622



# Random Forests


In [130]:
# fit
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [131]:
# predict
rfc_pred = rfc.predict(X_test)

In [132]:
print(confusion_matrix(y_test,rfc_pred))
print('\n')
print(classification_report(y_test,rfc_pred))

[[858 450]
 [489 825]]


              precision    recall  f1-score   support

           0       0.64      0.66      0.65      1308
           1       0.65      0.63      0.64      1314

    accuracy                           0.64      2622
   macro avg       0.64      0.64      0.64      2622
weighted avg       0.64      0.64      0.64      2622



# Random Forests with significant var by LR
 

In [133]:
X = df[['prev_CW/SA_rate', 'type_d', 'segmentName_d', 'net_pay', 'prev_CW/SA_rate']]
Y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.30)

In [134]:
# fit
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [135]:
# predict
rfc_pred = rfc.predict(X_test)

In [136]:
print(confusion_matrix(y_test,rfc_pred))
print('\n')
print(classification_report(y_test,rfc_pred))

[[893 439]
 [545 745]]


              precision    recall  f1-score   support

           0       0.62      0.67      0.64      1332
           1       0.63      0.58      0.60      1290

    accuracy                           0.62      2622
   macro avg       0.63      0.62      0.62      2622
weighted avg       0.63      0.62      0.62      2622

